"""ReportLab PDF export for employee onboarding submissions (A4; no storage paths)."""

from __future__ import annotations

import html
import re
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    Image,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.modules.onboarding.presentation import OnboardingExportDocument, format_file_size

_MARGIN = 14 * mm
_SIG_MAX_W = 70 * mm
_SIG_MAX_H = 28 * mm


class _NumberedCanvas(canvas.Canvas):
    """Two-pass canvas so footers can show Page X of Y."""

    def __init__(self, *args: Any, footer_left: str = "Generated by TimIQ", **kwargs: Any) -> None:
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._saved_page_states: list[dict[str, Any]] = []
        self._footer_left = footer_left

    def showPage(self) -> None:  # noqa: N802
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:
        page_count = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_footer(page_count)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def _draw_footer(self, page_count: int) -> None:
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#6b7280"))
        y = 10 * mm
        self.drawString(_MARGIN, y, self._footer_left[:80])
        label = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(A4[0] - _MARGIN, y, label)
        self.restoreState()


def _p(text: str, style: ParagraphStyle) -> Paragraph:
    return Paragraph(html.escape(text or "—").replace("\n", "<br/>"), style)


def _signature_image(image_bytes: bytes) -> Any | None:
    try:
        bio = BytesIO(image_bytes)
        reader = ImageReader(bio)
        iw, ih = reader.getSize()
        if iw <= 0 or ih <= 0:
            return None
        # Force decode early so platypus draw does not fail mid-build.
        reader.getRGBData()
        scale = min(_SIG_MAX_W / float(iw), _SIG_MAX_H / float(ih))
        img = Image(BytesIO(image_bytes), width=iw * scale, height=ih * scale)
        img.hAlign = "LEFT"
        return img
    except Exception:
        return None


def build_onboarding_submission_pdf(doc: OnboardingExportDocument) -> bytes:
    styles = getSampleStyleSheet()
    title_s = ParagraphStyle(
        "OnbTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=16,
        leading=20,
        spaceAfter=6,
        textColor=colors.HexColor("#111827"),
    )
    h2 = ParagraphStyle(
        "OnbH2",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        spaceBefore=8,
        spaceAfter=4,
        textColor=colors.HexColor("#111827"),
    )
    meta_s = ParagraphStyle(
        "OnbMeta",
        parent=styles["Normal"],
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#1f2937"),
    )
    cell_s = ParagraphStyle(
        "OnbCell",
        parent=styles["Normal"],
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#111827"),
    )
    label_s = ParagraphStyle(
        "OnbLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#374151"),
    )
    muted_s = ParagraphStyle(
        "OnbMuted",
        parent=styles["Normal"],
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#6b7280"),
    )

    buf = BytesIO()
    pdf = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=_MARGIN,
        rightMargin=_MARGIN,
        topMargin=_MARGIN,
        bottomMargin=18 * mm,
        title=doc.document_title,
        author="TimIQ",
    )

    story: list[Any] = []
    story.append(_p(doc.document_title, title_s))
    story.append(_p(f"Company: {doc.company_name}", meta_s))
    story.append(_p(f"Employee: {doc.employee_name}", meta_s))
    if doc.employee_email:
        story.append(_p(f"Email: {doc.employee_email}", meta_s))
    story.append(_p(f"Generated: {doc.generated_display}", meta_s))
    story.append(_p(f"Reference: {doc.submission_id}", muted_s))
    story.append(Spacer(1, 3 * mm))

    # Submission meta table
    story.append(_p("Submission information", h2))
    meta_rows = [
        [_p("Status", label_s), _p(doc.status, cell_s)],
        [_p("Submitted", label_s), _p(doc.submitted_display, cell_s)],
        [_p("Contract accepted", label_s), _p(doc.contract_accepted, cell_s)],
        [_p("Contract version", label_s), _p(doc.contract_version, cell_s)],
    ]
    usable = A4[0] - 2 * _MARGIN
    meta_table = Table(meta_rows, colWidths=[48 * mm, usable - 48 * mm])
    meta_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#d1d5db")),
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f8fafc")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ],
        ),
    )
    story.append(meta_table)

    # Signature
    sig_bits: list[Any] = [_p("Employee signature", h2)]
    sig_bits.append(_p(f"Signature mode: {doc.signature_mode}", meta_s))
    if doc.signatory_name:
        sig_bits.append(_p(f"Typed / signatory name: {doc.signatory_name}", meta_s))
    if doc.signature_image_bytes:
        img = _signature_image(doc.signature_image_bytes)
        if img is not None:
            sig_bits.append(Spacer(1, 2 * mm))
            sig_bits.append(img)
        else:
            sig_bits.append(_p("Signature unavailable", muted_s))
    elif doc.signature_error:
        sig_bits.append(_p(doc.signature_error, muted_s))
    else:
        sig_bits.append(_p("Not provided", muted_s))
    story.append(KeepTogether(sig_bits))

    # Documents register
    story.append(_p("Uploaded documents", h2))
    doc_header = [
        _p("Type", label_s),
        _p("Filename", label_s),
        _p("File type", label_s),
        _p("Size", label_s),
    ]
    doc_data: list[list[Any]] = [doc_header]
    if doc.documents:
        for row in doc.documents:
            doc_data.append(
                [
                    _p(row.doc_type_label, cell_s),
                    _p(row.original_filename, cell_s),
                    _p(row.content_type, cell_s),
                    _p(format_file_size(row.file_size_bytes), cell_s),
                ],
            )
    else:
        doc_data.append([_p("No documents", cell_s), _p("—", cell_s), _p("—", cell_s), _p("—", cell_s)])
    docs_table = Table(
        doc_data,
        colWidths=[42 * mm, usable - 42 * mm - 38 * mm - 22 * mm, 38 * mm, 22 * mm],
        repeatRows=1,
    )
    docs_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f3f4f6")),
                ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#d1d5db")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ],
        ),
    )
    story.append(docs_table)

    # Form responses
    story.append(_p("Form responses", h2))
    form_header = [_p("Field", label_s), _p("Response", label_s)]
    form_data: list[list[Any]] = [form_header]
    if doc.form_rows:
        for _key, label, value in doc.form_rows:
            form_data.append([_p(label, cell_s), _p(value[:8000], cell_s)])
    else:
        form_data.append([_p("No form data", cell_s), _p("—", cell_s)])
    form_table = Table(form_data, colWidths=[58 * mm, usable - 58 * mm], repeatRows=1)
    form_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f3f4f6")),
                ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#d1d5db")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ],
        ),
    )
    story.append(form_table)

    footer_left = f"Generated by TimIQ · {doc.generated_display}"
    pdf.build(
        story,
        canvasmaker=lambda *a, **k: _NumberedCanvas(*a, footer_left=footer_left, **k),
    )
    return buf.getvalue()


def onboarding_pdf_filename(employee_name: str, generated_at) -> str:
    """Safe download name: TimIQ_Onboarding_<Name>_<YYYY-MM-DD>.pdf"""
    raw = re.sub(r"[^A-Za-z0-9]+", "_", (employee_name or "").strip())
    safe = raw.strip("_") or "Employee"
    safe = safe[:80]
    date_part = generated_at.strftime("%Y-%m-%d") if generated_at is not None else "export"
    return f"TimIQ_Onboarding_{safe}_{date_part}.pdf"


def count_pdf_pages(pdf_bytes: bytes) -> int:
    return len(re.findall(rb"/Type\s*/Page(?![s\w])", pdf_bytes))


def pdf_text_haystack(pdf_bytes: bytes) -> bytes:
    """Best-effort decompress of PDF content streams for text smoke assertions."""
    import zlib

    from reportlab.pdfbase.pdfutils import asciiBase85Decode

    chunks: list[bytes] = [pdf_bytes]
    for m in re.finditer(rb"stream\r?\n(.*?)endstream", pdf_bytes, re.S):
        data = m.group(1)
        if data.endswith(b"\r\n"):
            data = data[:-2]
        elif data.endswith(b"\n"):
            data = data[:-1]
        # ReportLab often wraps page content as ASCII85 + Flate.
        try:
            data = asciiBase85Decode(data.decode("latin-1"))
        except Exception:
            pass
        try:
            chunks.append(zlib.decompress(data))
        except Exception:
            chunks.append(data if isinstance(data, (bytes, bytearray)) else bytes(data))
    return b"\n".join(chunks)


def pdf_embedded_image_count(pdf_bytes: bytes) -> int:
    return len(re.findall(rb"/Subtype\s*/Image\b", pdf_bytes))
