/**
 * Build full locale TS files from en.ts + partial overrides + patch bundles.
 * Run: node scripts/generate-locales.mjs
 */
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

import esPatch from "./locale-patches/es.mjs";
import plMissing from "./locale-patches/pl-missing.mjs";
import roMissing from "./locale-patches/ro-missing.mjs";
import ruPatch from "./locale-patches/ru.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const i18nDir = path.join(__dirname, "..", "src", "lib", "i18n");

function loadTsConst(filePath, constName) {
  const full = fs.readFileSync(filePath, "utf8").replace(/^\uFEFF/, "");
  const start = full.indexOf(`export const ${constName}`);
  if (start < 0) throw new Error(`Missing ${constName} in ${filePath}`);
  const nextExport = full.indexOf("export const", start + 12);
  const slice = nextExport > start ? full.slice(start, nextExport) : full.slice(start);
  let src = slice
    .replace(/:\s*Partial<Record<string,\s*string>>/g, "")
    .replace(/:\s*Record<string,\s*string>/g, "")
    .replace(`export const ${constName}`, `const ${constName}`);
  const sandbox = { module: { exports: {} } };
  vm.runInNewContext(`${src}\nmodule.exports = ${constName};`, sandbox);
  return sandbox.module.exports;
}

function writeLocaleTs(outPath, constName, strings) {
  const lines = [
    `/** Generated by scripts/generate-locales.mjs — run that script after editing patches. */`,
    `export const ${constName}: Record<string, string> = {`,
  ];
  for (const [k, v] of Object.entries(strings).sort(([a], [b]) => a.localeCompare(b))) {
    const esc = String(v)
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      .replace(/\r/g, "")
      .replace(/\n/g, "\\n");
    const keyEsc = k.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    lines.push(`  "${keyEsc}": "${esc}",`);
  }
  lines.push("};", "");
  fs.writeFileSync(outPath, lines.join("\n"), "utf8");
}

function mergeFull(en, partial, patch) {
  const out = { ...en };
  for (const [k, v] of Object.entries(partial)) {
    if (v != null && v !== "") out[k] = v;
  }
  for (const [k, v] of Object.entries(patch)) {
    if (v != null && v !== "") out[k] = v;
  }
  return out;
}

const en = loadTsConst(path.join(i18nDir, "en.ts"), "EN_STRINGS");
const legacyPath = path.join(__dirname, "overrides.legacy.ts");
const roPartial = loadTsConst(legacyPath, "RO_STRINGS");
const plPartial = loadTsConst(legacyPath, "PL_STRINGS");

const ro = mergeFull(en, roPartial, roMissing);
const pl = mergeFull(en, plPartial, plMissing);
const es = mergeFull(en, {}, esPatch);
const ru = mergeFull(en, {}, ruPatch);

writeLocaleTs(path.join(i18nDir, "ro.ts"), "RO_STRINGS", ro);
writeLocaleTs(path.join(i18nDir, "pl.ts"), "PL_STRINGS", pl);
writeLocaleTs(path.join(i18nDir, "es.ts"), "ES_STRINGS", es);
writeLocaleTs(path.join(i18nDir, "ru.ts"), "RU_STRINGS", ru);

const enKeys = Object.keys(en);
for (const [name, map] of [
  ["ro", ro],
  ["pl", pl],
  ["es", es],
  ["ru", ru],
]) {
  const missing = enKeys.filter((k) => !(k in map) || map[k] === "");
  if (missing.length) {
    console.error(`${name}: missing ${missing.length} keys`);
    process.exit(1);
  }
}
console.log(`Generated ro/pl/es/ru with ${enKeys.length} keys each.`);
