"""add employee location access

Revision ID: c94b9f1779d1
Revises: cca76e417105
Create Date: 2026-05-08 22:26:00.597898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94b9f1779d1'
down_revision: Union[str, Sequence[str], None] = 'cca76e417105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_location_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'location_id', name='uq_employee_location_access_user_location')
    )
    op.create_index(op.f('ix_employee_location_access_location_id'), 'employee_location_access', ['location_id'], unique=False)
    op.create_index(op.f('ix_employee_location_access_user_id'), 'employee_location_access', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_location_access_user_id'), table_name='employee_location_access')
    op.drop_index(op.f('ix_employee_location_access_location_id'), table_name='employee_location_access')
    op.drop_table('employee_location_access')
    # ### end Alembic commands ###
